### ISSUE TITLE
A *plea* to include binary API required by socket.io into NodeJS core.

### ISSUE THREAD

**Issue by tohagan** [Automattic/socket.io#1694]
I just posted this request to add the binary API required by socket.io into CORE node code -rather than force every Windows node app user to have an outdated SDK and compiler installed.  

  https://github.com/joyent/node/issues/8005

Most end users
- (a) don't have admin privs 
- (b) are not developers or experienced IT techs
- (c) don't have Visual Studio installed 
- (d) If they do use Visual Studio they ditched Visual Studio 2010 long ago. 

To make matters worse .. attempts to download the SDK from Microsoft failed with MS having the wrong links.

Once again I'm hitting this `ten pound gorilla` that refuses to go away. IMHO, I think requiring every node end user lib to tick all these boxes if their app wants to use `socket.io` is the wrong solution - the binary API belongs as part of node code so the compiler/SDK problem is no longer.

**Comment by rase-** [comment]
@tohagan I think this issue is a little premature.

Right now there are no signs of `ws` moving to node.js core. Whether that happens or not is out our hands. If that happens at some point we can revisit this issue and start using the core provided module instead.

The native code in `ws` is anyway optional and there is a fallback js implementation that will be used if the compilation failed, so there are no other usage drawbacks than some performance loss.
