### ISSUE TITLE
Get Started: Chat  - not working. 

### ISSUE THREAD

**Issue by faurehu** [Automattic/socket.io#2035]
I am following this instructions: http://socket.io/get-started/chat/

This script 
     /script src="/socket.io/socket.io.js"></script>
     /script>
       var socket = io();
     //script>
cannot load the client socket file. 

I have used '/' instead of the lines' first '<' to be able to display the code.

**Comment by faurehu** [comment]
My bad.

**Comment by worp1900** [comment]
Not sure if this is actually a problem, but I ran into the issue that Chrome would not bind to the submit event of the form on document.ready, using the example code provided in the chat-tutorial.

```
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.js"></script>
<script>
  var socket = io();
  $('form').submit(function(){
    socket.emit('chat message', $('#m').val());
    $('#m').val('');
    return false;
  });
</script>
```

Only after wrapping it in jquery.documentReady like this:

```
<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script>
	$( document ).ready(function() {
		var socket = io();
				
		$('form').submit(function(e){
			e.preventDefault();
			console.log('event triggered');
			socket.emit('chat message', $('#m').val());
			$('#m').val('');
			return false;
		});
	});
</script>
```

I was able to catch the event. Otherwise it would trigger a page reload and a "user disconnected/user connected" message in the cmd line.

Maybe it would make sense to add it to the tutorial? Or am I doing somehting wrong?

Cheers
Worp

**Comment by hawkeyeP** [comment]
For anyone else reading this old post, worp1900 's suggestion worked for me after trying many other options.  Thanks!
