### ISSUE TITLE
why i failed to install socket.io on win7 x64 with vs 2013?

### ISSUE THREAD

**Issue by chapgaga** [Automattic/socket.io#2128]
i try to install socket.io using `npm install socket.io` but failed, what's wrong?

![](http://img.itc.cn/photo/jRlckEjuhtW)
http://img.itc.cn/photo/jRlckEjuhtW.jpg

the details is here:

http://pastie.org/10204601

**Comment by suvil** [comment]
Read https://github.com/Automattic/socket.io/issues/2057

It's caused by an outdated version of ws installed by engine.io

For the time being you could either update ws or run 
```
npm install -g automattic/socket.io
```

**Comment by chapgaga** [comment]
@suvil why engine.io don't use latest ws?

**Comment by cchamberlain** [comment]
@chapgaga - sounds like you have npm installed to default location which requires sudo when installing global modules.

**Comment by chapgaga** [comment]
@cchamberlain i run with adim priviledge on windows 7, in fact, ** i can install other packages without any errors**

**Comment by cchamberlain** [comment]
@chapgaga - It looks like you are using the cygwin variety of Git.  I'd recommend installing latest msysgit if you don't have it and give that a shot.

Appears to be the same sort of error and some reporting msysgit upgrade fixed it - https://github.com/atom/atom/issues/5202

**Comment by Karnith** [comment]
@Chamberlain his compiler is visual studio, as seen by the .vcxproj and he's on windows. This is a known issue and has to do with an old ws version from engine.io not compiling.

**Comment by cchamberlain** [comment]
@Karnith the original error was related to ws, however the [later error](http://pastie.org/private/x7iwcnog8fqxo956luicw) I was referring to is related to npm not supporting Cygwin.  I know this because I fixed it in my own MSYS2 installation last night by [forking npm](https://github.com/cchamberlain/npm-msys2).  The issue is that npm does not do any detection for Cygwin/MINGW/MSYS2 and attempts to install with default Windows even though the git client is expecting Linux style paths and shell is expecting paths to start at the root instead of a drive.

If you take a look at the error below you can see that the issue lies in npm squashing the cygdrive path with the F:\ path where npm cache is located on his machine -

`ERR! fatal: '/cygdrive/f/npm/cache/_git-remotes/ssh-git-github-com-automattic-socket-io-6e1fd963/F:\npm\cache\_git-remotes\ssh-git-github-com-automattic-socket-io-6e1fd963' does not appear to be a git repository.`

So far I've got this portion of my fork working (for me) but am planning on working on a few issues today related to other npm functions.  My goal is to patch in the support for variants of Windows so that there is no impact to other platforms, and if I get to that point I'll offer it up as a pull request to upstream.  If they decide to integrate, awesome, if not I don't mind keeping the fork maintained to support my needs.

**Comment by rauchg** [comment]
Fixed
